version: '3'

services:
 
  pyramidapp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_paste
    environment:
      APP_PORT: 6014
    ports:
      - "0.0.0.0:6014:6014"
  flaskapp:
    build:
      context: ./flask
      dockerfile: Dockerfile
    environment:
      APP_PORT: 6000
      JAVA_HOME: "/usr/lib/jvm/default-java"
      PATH: $JAVA_HOME/bin:/appdynamics/flask/javaapp/gradle-6.5.1/bin:$PATH"
    ports:
      - "0.0.0.0:6000:6000"
  javaapp:
    stdin_open: true
    tty: true
    build:
      context: ./javaapp
      dockerfile: Dockerfile
    environment:
      APP_PORT: 8080
      JAVA_HOME: "/usr/lib/jvm/default-java"
      PATH: $JAVA_HOME/bin:/appdynamics/flask/javaapp/gradle-6.5.1/bin:$PATH"
    ports:
      - "0.0.0.0:8080:8080"
